### ISSUE TITLE
background subtractor cv2 function

### ISSUE THREAD

**Issue by MjBordalo** [nicholaskajoh/Vehicle-Counting#1]
Ỹou might would like to check the cv2 background subtraction function
 cv2.createBackgroundSubtractorMOG2()

**Comment by nicholaskajoh** [comment]
I know about the [background subtraction algorithms OpenCV has](https://docs.opencv.org/3.1.0/db/d5c/tutorial_py_bg_subtraction.html). I wanted to implement it myself in order to understand how it actually works.
