### ISSUE TITLE
Error when running in colab: cannot connect to X server

### ISSUE THREAD

**Issue by srdg** [nicholaskajoh/Vehicle-Counting#14]
I set the colab environment up according to instructions and when I went on to run the main file, i got this error `: cannot connect to X server` which is what pops up when there is no display to connect to. Is there any way to remove this display option and simply record the output somewhere, so that this might be working in a server? 
Just for information, I used the `--record` argument as well.

**Comment by nicholaskajoh** [comment]
I've actually had this in mind for some time now. I'll work on adding this option over the weekend. For now, you can comment `cv2.imshow('tracking', resized_frame)`.

**Comment by nicholaskajoh** [comment]
Hi @srdg! You can now use the `--headless` argument to run the VCS without a UI display.
