### ISSUE TITLE
yolov3.weights

### ISSUE THREAD

**Issue by yemikudaisi** [nicholaskajoh/Vehicle-Counting#2]
Hi, I'm trying to run your project and followed the instruction in setup but can't seem to get it to work. Apparently, I still needs to get the pretrained Yolo3 weights from another source.

So I suggest you state it in the setup and add a source to the weight as well.
I think it can be gotten from by running ``wget https://pjreddie.com/media/files/yolov3.weights``

Just to be sure, is it the same weight you used ?

**Comment by nicholaskajoh** [comment]
_yolov3.weights_ should be placed in the _detectors_ folder.

**Comment by nicholaskajoh** [comment]
I thought I stated that in the README. It was an oversight. Can you send a PR?

**Comment by nicholaskajoh** [comment]
Yes it is. I thought I stated that in the README. It was an oversight. Can you send a PR?

FYI, _yolov3.weights_ should be placed in the _detectors_ folder.
