### ISSUE TITLE
No module dotenv

### ISSUE THREAD

**Issue by ChunmianLin** [nicholaskajoh/Vehicle-Counting#24]
Hi, I encounted new problem. When I used 'tfoda' to detect object of interest, an error was noted as follows. How can I do next to solve, and I cannot determine whether my pretrained model downloaded from 'https://github.com/opencv/opencv/wiki/TensorFlow-Object-Detection-API#use-existing-config-file-for-your-model', is wrong. I don't find weight and config file, could you please help me to continue?
Thanks in advance.
![2019-08-17 09-19-08屏幕截图](https://user-images.githubusercontent.com/53289159/63205032-ee954000-c0d0-11e9-8a74-c7a3b34da2b6.png)

**Comment by nicholaskajoh** [comment]
Your screenshot shows that _python-dotenv_ isn't installed. Run `pip install -r requirements.txt`.

**Comment by ChunmianLin** [comment]
Thanks. I have done!
