### ISSUE TITLE
Error in path to 'WEIGHTS_PATH' and 'CONFIG_PATH'

### ISSUE THREAD

**Issue by b-thebest** [nicholaskajoh/Vehicle-Counting#25]
It's giving error like this : Vehicle-Counting-master/detectors/yolo/yolo_detector.py", line 20, in get_bounding_boxes
    net = cv2.dnn.readNet(os.getenv('WEIGHTS_PATH'), os.getenv('CONFIG_PATH'))
cv2.error: OpenCV(4.1.0) /io/opencv/modules/dnn/src/dnn.cpp:3780: error: (-2:Unspecified error) Cannot determine an origin framework of files:  in function 'readNet'

Please help me to resolve this

**Comment by nicholaskajoh** [comment]
Please refer to the __Notes__ section of the README. You need to create an environment file for YOLO and specify the paths to a weights and config file.
