### ISSUE TITLE
From where to Download all these files

### ISSUE THREAD

**Issue by b-thebest** [nicholaskajoh/Vehicle-Counting#26]
WEIGHTS_PATH=/home/nicholas/dev/Vehicle-Counting/detectors/yolo/downloads/yolov3.weights
CONFIG_PATH=/home/nicholas/dev/Vehicle-Counting/detectors/yolo/downloads/yolov3.cfg
CLASSES_PATH=/home/nicholas/dev/Vehicle-Counting/detectors/yolo/downloads/coco.classes.txt
CLASSES_OF_INTEREST_PATH=/home/nicholas/dev/Vehicle-Counting/detectors/yolo/downloads/coco_interest.classes.txt

**Comment by nicholaskajoh** [comment]
Here: https://pjreddie.com/darknet/yolo/.

For the classes list, see #23.

Please take out time to go through the README.

Cheers!
