### ISSUE TITLE
OS dependency

### ISSUE THREAD

**Issue by theMAC9** [nicholaskajoh/Vehicle-Counting#31]
Hey, is it correct that .env files are only usable on Linux based distributions?

Is there a way to use this on Windows - e.g. you could determine the os at the start and then just use default variables instead of the os.getenv command. If needed, I or other users could switch these out. It would be great for a more flexible usage regarding OS.

Thanks.

**Comment by nicholaskajoh** [comment]
Hi @theMAC9! .env files work on all OSes AFAIK. What issue are you experiencing with Windows?
