### ISSUE TITLE
Not able to run 

### ISSUE THREAD

**Issue by mssudarsan** [nicholaskajoh/Vehicle-Counting#32]
Hi 

I have tried by cloning your repository.... getting erros as follows: 

(i) If i run "python -m main" in terminal --> ImportError: No module named detectors.detector

(ii) If i run "python3 main.py" in terminal --> ModuleNotFoundError: No module named 'dotenv'

Thanks in advance

**Comment by nicholaskajoh** [comment]
Hi @mssudarsan!

1. There's in fact a module called detectors.detector. Here: https://github.com/nicholaskajoh/Vehicle-Counting/blob/master/detectors/detector.py. Are you sure you're running this command from the project's root directory?

2. Have you installed the dependencies in requirements.txt? __dotenv__ is one of them. See: https://github.com/nicholaskajoh/Vehicle-Counting/blob/346893d8f6648d9eec3e6ee278e17fad2f5278e9/requirements.txt#L3.

If you still have any issues feel free to share. Cheers!

**Comment by mssudarsan** [comment]
1. Yes, i had run it from root directory only.

2. Yes have installed all packages using "pip install -r requirements.txt"

suggest me where i'm wrong in cloning it, thank you

**Comment by mssudarsan** [comment]
Yeah, again had followed the steps mentioned in readme :
Everything get successfully installed and run the commands "python -m main " and "python3 main.py" got the following issue: 
 
File "/usr/lib/python3.6/ast.py", line 84, in _convert
    raise ValueError('malformed node or string: ' + repr(node))
ValueError: malformed node or string: None

How can i resolve it. Thank you in advance

**Comment by mssudarsan** [comment]
Thank you i resolved it :)
