### ISSUE TITLE
What is the "coco_interest.classes.txt"?

### ISSUE THREAD

**Issue by ZYT1122** [nicholaskajoh/Vehicle-Counting#35]
Can you tell me what the "coco_interest.classes.txt" looks like ?     
or   Where can I get  this file？

**Comment by ZYT1122** [comment]
Looking forward to your reply ！！！ Thank you！！！

**Comment by nicholaskajoh** [comment]
Hey @ZYT1122!

Sorry for the late reply.

I've renamed these files several times. Forgive me!

**coco_interest.classes.txt** or **classes_of_interest.txt** or **coco_classes_of_interest.txt** contains:

```
bicycle
car
truck
motorcycle
bus
```

Cheers!
