### ISSUE TITLE
Nice Project can you add counting based on Vehicle classification type like car, Bike, Truck, Bus??

### ISSUE THREAD

**Issue by amaadmirza** [nicholaskajoh/Vehicle-Counting#4]

**Comment by nicholaskajoh** [comment]
Can you throw more light on what exactly you want to accomplish? Some detectors (`yolo`, `ssd`) can classify vehicles, others can't (`bgsub`, `haarc`). It's just a matter of changing a few lines of code to get the classification working but I need to know what you want to do/have in mind.

**Comment by amaadmirza** [comment]
mean if you separate  count car, separte count truck and separate count bus when they cross the ROI

**Comment by nicholaskajoh** [comment]
Okay. It's possible.

**Comment by nicholaskajoh** [comment]
Okay. It's possible. You can return bounding boxes along with the classes of objects detected. While this is easy to do, I feel it'll complicate the application as a whole. Any specific reason why you want this?
I think a better approach would be to save images of each vehicle once counted to be processed by another program solely created for vehicle classification. Images may also be used for other purposes such as vehicle identification (ANPR).

**Comment by Ashlin-Siby** [comment]
@nicholaskajoh  it would be great if you could tell where exactly to return the claass of the object?

**Comment by nicholaskajoh** [comment]
You can return the classes in _detectors/yolo/yolo_detector.py_ like so: 

```python
classes = [] # step 1

for output in outputs:
    for detection in output:
        # ...
        if confidence > 0.5 and classes[class_id] in classes_of_interest:
            # ...
            classes.append(classes[class_id]) # step 2
# ...
return _bounding_boxes, classes # step 3
```

**Comment by nicholaskajoh** [comment]
You can return the classes in _detectors/yolo/yolo_detector.py_ like so: 

```python
_classes = [] # step 1

for output in outputs:
    for detection in output:
        # ...
        if confidence > 0.5 and classes[class_id] in classes_of_interest:
            # ...
            classes.append(classes[class_id]) # step 2
# ...
return _bounding_boxes, _classes # step 3
```
