### ISSUE TITLE
ModuleNotFoundError: No module named 'utils.detection_roi'

### ISSUE THREAD

**Issue by mjbedford2017** [nicholaskajoh/Vehicle-Counting#9]
Hello. Love the project so far. However, followed the readme exactly as you typed it by cloning/downloading the latest version as of today. I also installed all pre-requisites. 

However, when I run it, I get the following error:
Traceback (most recent call last):
  File "Vehicle_Counting.py", line 11, in <module>
    from utils.detection_roi import get_roi_frame, draw_roi
ModuleNotFoundError: No module named 'utils.detection_roi'

Because I downloaded the whole thing and am running from the folder structure as you have it layed out, I have confirmed that there is a utils folder and inside of the folder is the detection_roi file in there so I cannot figure out why it says not found. 

Thanks!

**Comment by yemikudaisi** [comment]
Hi, I just cloned the repo all over again and it doesn't seem to produce the same error. I'm guessing it has something to do with the way modules are imported in different versions of python, which version of python are you working with ?

**Comment by mjbedford2017** [comment]
Python 3.6.7 is what I am running currently. It should be worth noting I am running Python on Windows. I am not sure if that has anything to do with it?

**Comment by yemikudaisi** [comment]
@mjbedford2017 I run python 3.7.2 on Windows 10 and it works just fine. It's strange, can't seem to reproduce the issue.

**Comment by mjbedford2017** [comment]
Okay, well, thanks for trying. I will try to re-do the download and everything from scratch to see if that works. Thanks!
